version: 2.1
jobs:
  build-then-check-eslint:
    branches:
      ignore:
        - master
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint

  build-then-deploy:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .    
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_DEPLOY_TOKEN"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build-then-check-eslint      
      - build-then-deploy
