version: 2.1
jobs:
  build-then-deploy:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
      - run:
            name: Install Dependencies
            command: npm install
      - save_cache:
            key: v1-npm-deps-{{ checksum "package-lock.json" }}
            paths:
                - ./node_modules
      - run: yarn lint
      - run:
            name: Build
            command: npm build
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
