version: 2.1
jobs:
  build-job:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint

  deploy-job:
    docker:
      - image: circleci/node:12.9.1-browsers
    working_directory: /tmp/my-project
    steps:
      - run:
          name: Install Firebase Tools
          command: yarn add --prefix=./firebase-deploy firebase-tools
      - run:
          name: Deploy Master to Firebase
          command: ./firebase-deploy/node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
